### PR TITLE
fix(pruning): changes image planning for pruning operations to use the destination image repo

### LINKED ISSUE #447: [BUG] image pruning operation attempts to delete release images in wrong location
# Version

```console
$ oc-mirror version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.2.0-alpha.1-29-g4849560", GitCommit:"4849560f", GitTreeState:"dirty", BuildDate:"2022-05-04T21:26:46Z", GoVersion:"go1.18", Compiler:"gc", Platform:"linux/amd64"}
```

# What happened?

When attempting to prune an OCP release from an imageset the target repository is incorrect resulting in a 404.

# What did you expect to happen?

The release images to be pruned from the correct repository.

# How to reproduce it (as minimally and precisely as possible)?

```
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  local:
    path: metadata
mirror:
  platform:
    channels:
    - name: stable-4.9
```
```
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  local:
    path: metadata
mirror:
  platform:
    channels:
    - name: stable-4.10
```

Mirror with the first configuration and then again with the second to reproduce.
```console
$ ./bin/oc-mirror --config imageset-config.yaml docker://localhost:5000
```

# Anything else we need to know?

# References

Enter text here.

### PR DESCRIPTION
**Pull request by jpower432**
# Description

Currently, the source repo and destination repo for OCP releases are not the same. This causes the image pruning planning operation to add an image in the wrong repository to the mapping. The association path which defines the destination (in the archive or registry) is used in planning with this change to determine the correct image repository information.

Fixes #447

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [X] Manually tested with releases

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jpower432** [comment]
cc @jharmison-redhat FYI on the changes to the default location of the release images.

**Comment by jharmison-redhat** [comment]
This change would require that on the disconnected side we use that exact namespace, is that correct? No nesting?

**Comment by jpower432** [comment]
> This change would require that on the disconnected side we use that exact namespace, is that correct? No nesting?

@jharmison-redhat As discussed, putting this back in the draft to rethink the solution to the issue.

**Review by dinhxuanvu — COMMENTED** [review]
Looking pretty straight forward. Please rebase and I'll lgtm on it.

**Review by dinhxuanvu — COMMENTED** [review]
/lgtm

**Pull request merged**
