### PR TITLE
CFE-768 - FollowUp: Fix usage of registries.conf for OCI feature

### PR DESCRIPTION
**Pull request by sherine-k**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Unit and E2E tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by lmzuccarelli — COMMENTED** [review]
As we walked through the code change and verified this in our peer programming session, this change looks good

**Comment by aguidirh** [comment]
It looks good to me.

**Comment by sherine-k** [comment]
/assign @soltysh 
Please can you take a look?
Thanks

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
