### PR TITLE
Bug 2069307: bump operator-registry dep v1.21.1

### PR DESCRIPTION
**Pull request by jpower432**
# Description

This change updates the operator-registry dependency to
commit de36104087733013025629d80bf8445045a8a6e7 to resolve
a bug when processing cyclic dependencies in operator bundles.

Fixes BZ 2065832

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [X] Manually verified that the Red Hat 4.10 catalog processing successfully

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by afflom** [comment]
@jpower, I've tested this and it does the thing. Do you want more eyes on it or can we send it?

**Comment by jpower432** [comment]
@afflom Should be fine, but I am trying to why the BZ is not being linked. Can you please assist?

**Comment by jpower432** [comment]
@dinhxuanvu @afflom Does this PR need any changes? If not, can you please approve?

**Comment by jpower432** [comment]
Thanks @dinhxuanvu. Rebased; should be good to re-review.

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Pull request merged**
