### PR TITLE
[release-4.10] chore: add vendor directory to repo for builds (#293)

### PR DESCRIPTION
**Pull request by jpower432**
This is a cherry-pick of #293
Signed-off-by: Jennifer Power <barnabei.jennifer@gmail.com>

### CODE REVIEW

**Review by dinhxuanvu — COMMENTED** [review]
/lgtm

**Comment by jpower432** [comment]
@bparees Can you please take a look at this and approve? Thank you!

**Comment by bparees** [comment]
overriding valid-bz req as there is nothing explicit to be tested here, needed to build the component successfully.

**Pull request merged**
