### PR TITLE
OCPBUGS-3414: fix: Missing 'ImageContentSourcePolicy' and 'CatalogSou…

### PR DESCRIPTION
**Pull request by flaper87**
# Description

Cherry picks PR e491750907450588a53b8cdd5f8f77eadf2d835e 

Related #540

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jpower432** [comment]
@flaper87 Does this PR still need a review? Looks like this may have been backported to 4.12 in another PR.

**Comment by flaper87** [comment]
> @flaper87 Does this PR still need a review? Looks like this may have been backported to 4.12 in another PR.

Yeah, I think this PR is now obsolete. @sherine-k  can you confirm? :pray:

**Comment by sherine-k** [comment]
Yes! it's ok to close this now : the fix is both in main and release-4.12

**Comment by flaper87** [comment]
Fantastic, thanks a bunch!

**Pull request closed without merging**
