### PR TITLE
OCPBUGS-23550: Generate both binaries for rhel8 and rhel9

### PR DESCRIPTION
**Pull request by sherine-k**
# Description

Creates 2 Dockerfiles, for rhel8 and rhel9.
This is aimed to replace the single Dockerfile.ci.

Fixes [OCPBUGS-23550](https://issues.redhat.com/browse/OCPBUGS-23550)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Automated tests (unit + e2e)

## Expected Outcome
Automated tests should pass

### CODE REVIEW

**Comment by sherine-k** [comment]
waiting for more instructions from @ardaguclu and @joepvd

**Comment by sherine-k** [comment]
After discussion with @ardaguclu , we are following the same path as https://github.com/openshift/oc/pull/1632 for oc: 
A single oc-mirror image is generated, and contains both oc-mirror.rhel8 and oc-mirror.rhel9.
This should also be enhanced by https://github.com/openshift/release/pull/46930 which should replace the base and builder images by images from the image streams.

**Comment by lmzuccarelli** [comment]
@sherine-k - so the final solution is to create 2 binary files using the same Dockerfile.ci , rather then 2 dockerfiles. I assume this is what oc and others are doing

**Comment by lmzuccarelli** [comment]
@sherine-k  Lets wait for the QE review before we add the relevant flags to merge

**Comment by sherine-k** [comment]
Hi @lmzuccarelli , Yes, this is how oc is resolving the issue. (https://github.com/openshift/oc/pull/1632)

**Comment by sherine-k** [comment]
Tested also using brew:
* https://github.com/openshift-eng/ocp-build-data/pull/4109
* https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2829862, which passes the sniff test
Thank you @joepvd

**Review by aguidirh — COMMENTED** [review]
/lgtm

**Pull request merged**
