### PR TITLE
OCPBUGS-37667: Rebuild catalogs -- without cache generation

### PR DESCRIPTION
**Pull request by sherine-k**
# Description

## What are we trying to fix?

According to OCPBUGS-35386, when the user mirrors operators and specifies a maxVersion < channel's jead, without catalog rebuild, the full catalog is sent to cluster. On cluster, when installing the operator without specifically selecting maxVersion , the OLM will attempt to install bundle at channel head and fail because that head version was never mirrored.

## What is the fix?

- `--rebuild-catalogs` is still here for backwards compatibility (so --rebuild-catalogs=false means we don't rebuild and still send the catalog as is, just in case anybody wants this?)
- it is marked deprecated, so that in the next release we can remove the flag if no one is using "full" catalogs
- the default value is true: so if omitted, catalog will be rebuilt, with following behavior
  - But we don't regenerate the internal cache
  - And we modify the CMD of the image from `opm serve /configs --cache-dir=/tmp/cache` to `opm serve /configs`
  - We choose not to whiteout `/tmp/cache` from the rebuilt image, because when `/tmp/cache` doesn't exist, `operator-registry` will attempt to [create a temp folder](https://github.com/operator-framework/operator-registry/blob/036918e6ea1c025bd6422883ce059e362be3e017/cmd/opm/serve/serve.go#L120-L126) under `/tmp/opm-serve-cache-1234568` and fails for lack of permission

## Impacts

:warning: This has an impact on the cluster, because this CMD change means that the cache will be calculated when the catalogsource is deployed to the cluster
  - The time needed to calculate this at startup depends on the catalog content, and CPU/memory allocated to the pod.
  - Starting 4.12 there's a startupProbe set to 100s . So if the cache calculation exceeds 100s, the catalog might not be able to start!
  - So it's probably important to test this on clusters , with catalogs having a lot of operators

Fixes OCPBUGS-35386 + OCPBUGS-37667

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
with the following 2 imagesetconfigs, here are the scenarios tested:
```mermaid
flowchart TD
A[OCPBUGS-35386] --> R{--rebuild-catalogs};
R -- True --> R1C{--build-catalog-cache};
R1C -- True --> R1C1{$OPM_BINARY?};
R1C -- False --> R1C2{catalog origin?};

R1C2 -- Registry based --> R1C2R[RegistryCatalog];
R1C2 -- OCI based --> R1C2O[OCICatalog];

R1C2R -->R1C2RN[No targetCatalog - No targetTag];
R1C2R --> R1C2RTT[TargetTag only];
R1C2R --> R1C2RTC[TargetCatalog only];
R1C2R --> R1C2RTTC[TargetCatalog + TargetTag];

R1C2O -->R1C2ON[No targetCatalog - No targetTag];
R1C2O -->R1C2OTT[TargetTag only];
R1C2O --> R1C2OTTC[TargetCatalog + TargetTag];

R1C1 -- True --> R1C1Y[$OPM_BINARY defined];
R1C1 -- False --> R1C1N[no $OPM_BINARY];

R1C1N --> R1C1NT{catalog origin?};
R1C1NT -- Registry based -->R1C1NTR[RegistryCatalog];
R1C1NT -- OCI based -->R1C1NTO[OCICatalog];

R1C1NTR --> R1C1NTRN[No targetCatalog - No targetTag]
R1C1NTR --> R1C1NTRTT[TargetTag only]
R1C1NTR --> R1C1NTRTC[TargetCatalog only]
R1C1NTR --> R1C1NTRTTC[TargetCatalog + TargetTag]

R1C1NTO --> R1C1NTON[No targetCatalog - No targetTag]
R1C1NTO -->R1C1NTOTT[TargetTag only]
R1C1NTO --> R1C1NTOTTC[TargetCatalog + TargetTag]

R1C1Y --> R1C1YT{catalog origin?};
R1C1YT -- Registry based -->R1C1YTR[RegistryCatalog];
R1C1YT -- OCI based -->R1C1YTO[OCICatalog];

R1C1YTR --> R1C1YTRN[No targetCatalog - No targetTag]
R1C1YTR --> R1C1YTRTT[TargetTag only]
R1C1YTR --> R1C1YTRTC[TargetCatalog only]
R1C1YTR --> R1C1YTRTTC[TargetCatalog + TargetTag]

R1C1YTO --> R1C1YTON[No targetCatalog - No targetTag]
R1C1YTO -->R1C1YTOTT[TargetTag only]
R1C1YTO --> R1C1YTOTTC[TargetCatalog + TargetTag]

R -- False --> R2T{catalog origin?};
R2T -- Registry based -->R2R[RegistryCatalog];
R2T -- OCI based -->R2O[OCICatalog];

R2R --> R2RN[No targetCatalog - No targetTag]
R2R --> R2RTT[TargetTag only]
R2R --> R2RTC[TargetCatalog only]
R2R --> R2RTTC[TargetCatalog + TargetTag]

R2O --> R2ON[No targetCatalog - No targetTag]
R2O -->R2OTT[TargetTag only]
R2O --> R2OTTC[TargetCatalog + TargetTag]
```

PS: from the diagram above, only 1 scenario with --build-catalog-cache + $OPM_BINARY was tested, but not the others.

### ImageSetConfig for registry based catalogs:

```yaml
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2

mirror:
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.14
    packages:
    - name: aws-load-balancer-operator
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.15
    targetCatalog: abc/redhat-operator-index
    packages:
    - name: external-dns-operator
  - catalog: registry.redhat.io/redhat/community-operator-index:v4.14
    targetTag: v0.0
    packages:
    - name: community-trivy-operator
  - catalog: registry.redhat.io/redhat/community-operator-index:v4.15
    targetCatalog: def/community-operator-index
    targetTag: v4.15-tt
    packages:
    - name: opentelemetry-operator
```

### ImageSetConfig for OCI based catalogs:

```yaml
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2

mirror:
  operators:
  - catalog: oci:///home/skhoury/OCPBUGS-35386/rhopi
    packages:
    - name: aws-load-balancer-operator
  - catalog: oci:///home/skhoury/OCPBUGS-35386/rhopi416
    targetCatalog: ghi/redhat-operator-index
    targetTag: v4.16
    packages:
    - name: external-dns-operator
  - catalog: oci:///home/skhoury/OCPBUGS-35386/coi414
    targetTag: v0.0
    packages:
    - name: community-trivy-operator
```

### Containerfile used to generate a catalog with a fake opm binary
```bash
FROM registry.redhat.io/redhat/redhat-operator-index:v4.12
USER root
RUN rm -fr /tmp/cache/*
RUN rm -f /usr/bin/opm /bin/registry/opm /usr/bin/registry/opm 
COPY toto.sh /bin/opm
RUN chmod +x /bin/opm
```
Using this Containerfile, do:
```bash
cat << 'EOF' > toto.sh
#!/bin/bash
echo toto
EOF
podman build -f Containerfile_noopm . -t localhost:5000/noopm/catalog:v4.12
 podman push localhost:5000/noopm/catalog:v4.12 --tls-verify=false
```
Then use imageSetConfig:
```yaml
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
mirror:
  operators:
  - catalog: localhost:5000/noopm/catalog:v4.12
    packages:
    - name: aws-load-balancer-operator
```
## Expected Outcome

# Mirroring should be successful
1. For catalogs with `--rebuild-catalogs=false`,
  * the rendered catalogs should have all the operator packages. This can be controlled using `opm render $mirrored_catalog_ref > /tmp/file.json` . If the mirror registry is HTTP only, use `--use-http`
  * the rendered catalogs should be runnable. This can be tested by:
    * applying the catalog source to cluster, pods should run
    * `podman pull $mirrored_catalog_ref; time podman run --rm $mirrored_catalog_ref` : the catalog should take some time to start. Time should be <100s. Log line `time="2024-07-31T13:14:35Z" level=info msg="serving registry" configs=/configs port=50051` should appear
2. For catalogs with `--build-catalog-cache`,
  * the rendered catalogs should have only selected packages. This can be controlled using `opm render $mirrored_catalog_ref > /tmp/file.json` . If the mirror registry is HTTP only, use `--use-http`
  * the rendered catalogs should be runnable. This can be tested by:
    * applying the catalog source to cluster, pods should run
    * `podman pull $mirrored_catalog_ref; time podman run --rm $mirrored_catalog_ref` : the catalog should run instantly.  Log line `time="2024-07-31T13:14:35Z" level=info msg="serving registry" configs=/configs port=50051` should appear

### CODE REVIEW

**Review by aguidirh — APPROVED** [review]
Thanks @sherine-k, this is a very important one.

It LGTM, let's wait for @kasturinarra to finish her tests and then we can merge it.

Thanks again :tada:

**Comment by kasturinarra** [comment]
so i tried to mirror about  ~45 and ~70 operators and i always saw the catalogsource pod coming up in about ~42 seconds, could not able to get all 103 operators mirroring as oc-mirror was hanging. Since the time taken for the catalogsource pod to be in a running state is ~42 seconds, adding lgtm here.

Tested using below steps:
=====================
1. Built oc-mirror from this PR
2. created 4.12 cluster
3. Mirrored operators
4. created catalogSource and verified that pod comes up running in about <100 seconds.
5. More details in thread https://redhat-internal.slack.com/archives/C050P27C71S/p1722260548956449

**Pull request merged**
