### PR TITLE
[release-4.16] CLID-138,OCPBUGS-34947: upgrades distribution/distribution for a released version

### PR DESCRIPTION
**Pull request by aguidirh**
# Description

Cherry-pich of [#864](https://github.com/openshift/oc-mirror/pull/864)

This PR upgrades the distribution/distribution to a version released in github ([v3.0.0-alpha.1](https://github.com/distribution/distribution/releases/tag/v3.0.0-alpha.1)) [which is the one recommended by the maintainers](https://github.com/distribution/distribution/discussions/4317#discussioncomment-8973790).

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes CVEs)

# How Has This Been Tested?

MirrorToMirror, MirrorToDisk and DiskToMirror on v2

It is necessary to still run the basic flows on v1.

## Expected Outcome

All the flows should finish successfully.

### CODE REVIEW

**Comment by lmzuccarelli** [comment]
@aguidirh - would you mind adding [release-4.16] in the title - makes it less confusing. Thanks

**Comment by sherine-k** [comment]
/retitle [release-4.16] CLID-138: upgrades distribution/distribution for a released version

**Comment by aguidirh** [comment]
> @aguidirh - would you mind adding [release-4.16] in the title - makes it less confusing. Thanks

Done @lmzuccarelli

**Pull request merged**
