### PR TITLE
CLID-100: Create API v2alpha1 for oc-mirror v2 TP

### PR DESCRIPTION
**Pull request by sherine-k**
# Description

This change bumps the api version used by v2 to `v2alpha1`, in anticipation for releasing the TP with v4.16.

Fixes # [CLID-5](https://issues.redhat.com//browse/CLID-5)
**:warning: ImageSetConfigs and DeleteImageSetConfigs used for v2 should now have `apiVersion: mirror.openshift.io/v2alpha1`**
cc @zhouying7780 + @kasturinarra : impacts automated tests of v2, polarion test cases.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Automatic e2e tests pass
Unit tests pass

### CODE REVIEW

**Comment by lmzuccarelli** [comment]
@sherine-k - this is a fairly large PR, my thinking here is lets wait for all other PR's to merge, I'm more than happy to give this "looks good to me" ,  its more important to get all feature dev asap , we can always spend time bug fixing afterwards

**Review by aguidirh — COMMENTED** [review]
It looks good to me as well. Maybe wait to other PRs merge before this one as @lmzuccarelli mentioned already.

**Pull request merged**
