### PR TITLE
[release-4.12] OCPBUGS-14065: fix: Limit the nested repository path while mirroring the images

### PR DESCRIPTION
**Pull request by aguidirh**
# Description

This fix is based on the fix created for 4.13 but only with essentials changes needed for 4.12

Based on #623 and #634 

Fixes # ([OCPBUGS-14065](https://issues.redhat.com/browse/OCPBUGS-14065))

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Review by sherine-k — APPROVED** [review]
/lgtm

**Comment by sherine-k** [comment]
/retitle [release-4.12] OCPBUGS-14065: fix: Limit the nested repository path while mirroring the images

**Comment by kasturinarra** [comment]
Below are the steps i have followed to test this:
======================================
1. clone the oc-mirror repor
2. git checkout release-4.12
3. gh pr checkout 642
4. make build
5. Run oc-mirror -h, verify that --max-nested-paths is present
`--max-nested-paths int            Number of nested paths, for destination registries that limit nested paths`
6. start a local docker registry by running the command `podman  run -d -p 5000:5000 -v /home/fedora/registry:/var/lib/registry/docker/registry --privileged  -e REGISTRY_STORAGE_DELETE_ENABLED=true --restart=always --name registry quay.io/openshifttest/registry@sha256:1106aedc1b2e386520bc2fb797d9a7af47d651db31d8e7ab472f2352da37d1b3`
7. Now run command `./oc-mirror --config /tmp/config.yaml docker://localhost:5000/knarra/mynamespace/myns1/local-storage-operator --dest-use-http` , see that it works fine by not specifying any `--max-nested-paths`
8. Now run command `./oc-mirror --config /tmp/config.yaml docker://quay.io/knarra/lso` to push contents to quay and see that slashes after "=" in the mapping.txt is not replaced by `-`
```
registry.redhat.io/redhat/redhat-operator-index:v4.12=quay.io/knarra/lso/redhat/redhat-operator-index:v4.12
registry.redhat.io/openshift4/ose-local-storage-diskmaker@sha256:398414dc2abad094c2e97a57514d69d5c80790510e19af105692f2864cc9c566=quay.io/knarra/lso/openshift4/ose-local-storage-diskmaker:df3814e9
registry.redhat.io/openshift4/ose-local-storage-operator@sha256:5f01648146118a5c156733f174addf7f64b794b1edda8e237fb42cb353222102=quay.io/knarra/lso/openshift4/ose-local-storage-operator:d7f3b07
registry.redhat.io/openshift4/ose-local-storage-operator-bundle@sha256:56386aaf90d66683b384a49b052f8b2ed7f969ef47d83b7e76badf2ddf5339e1=quay.io/knarra/lso/openshift4/ose-local-storage-operator-bundle:3dbae7c1
registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:116dbeb371324607d361d4f1a9daeb5890e44d29b96c9800b2b1d93d21635dec=quay.io/knarra/lso/openshift4/ose-kube-rbac-proxy:ec31b7f8
quay.io/openshifttest/bench-army-knife@sha256:078db36d45ce0ece589e58e8de97ac1188695ac155bc668345558a8dd77059f6=quay.io/knarra/lso/openshifttest/bench-army-knife:latest
```
```
---
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: generic-0
spec:
  repositoryDigestMirrors:
  - mirrors:
    - quay.io/knarra/lso/openshifttest
    source: quay.io/openshifttest
---
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  labels:
    operators.openshift.org/catalog: "true"
  name: operator-0
spec:
  repositoryDigestMirrors:
  - mirrors:
    - quay.io/knarra/lso/openshift4
    source: registry.redhat.io/openshift4
  - mirrors:
    - quay.io/knarra/lso/redhat
    source: registry.redhat.io/redhat
```

10. Now run command `./oc-mirror --config /tmp/config.yaml docker://quay.io/knarra/mynamespace/mynamespace1/lso --max-nested-paths=5` to push contents to quay and see that slashes after "=" in the mapping.txt is replaced by `-`
```
mapping.txt:
==============
quay.io/openshifttest/bench-army-knife@sha256:078db36d45ce0ece589e58e8de97ac1188695ac155bc668345558a8dd77059f6=quay.io/knarra/mynamespace/mynamespace1/lso/openshifttest-bench-army-knife:latest
registry.redhat.io/redhat/redhat-operator-index:v4.12=quay.io/knarra/mynamespace/mynamespace1/lso/redhat/redhat-operator-index:v4.12
registry.redhat.io/openshift4/ose-local-storage-operator@sha256:5f01648146118a5c156733f174addf7f64b794b1edda8e237fb42cb353222102=quay.io/knarra/mynamespace/mynamespace1/lso/openshift4-ose-local-storage-operator:d7f3b07
registry.redhat.io/openshift4/ose-local-storage-operator-bundle@sha256:56386aaf90d66683b384a49b052f8b2ed7f969ef47d83b7e76badf2ddf5339e1=quay.io/knarra/mynamespace/mynamespace1/lso/openshift4-ose-local-storage-operator-bundle:3dbae7c1
registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:116dbeb371324607d361d4f1a9daeb5890e44d29b96c9800b2b1d93d21635dec=quay.io/knarra/mynamespace/mynamespace1/lso/openshift4-ose-kube-rbac-proxy:ec31b7f8
registry.redhat.io/openshift4/ose-local-storage-diskmaker@sha256:398414dc2abad094c2e97a57514d69d5c80790510e19af105692f2864cc9c566=quay.io/knarra/mynamespace/mynamespace1/lso/openshift4-ose-local-storage-diskmaker:df3814e9
```

```
[fedora@preserve-fedora36 ~]$ cat oc-mirror-workspace/results-1685382321/imageContentSourcePolicy.yaml 
---
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: generic-0
spec:
  repositoryDigestMirrors:
  - mirrors:
    - quay.io/knarra/mynamespace/mynamespace1/lso
    source: quay.io/openshifttest
---
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  labels:
    operators.openshift.org/catalog: "true"
  name: operator-0
spec:
  repositoryDigestMirrors:
  - mirrors:
    - quay.io/knarra/mynamespace/mynamespace1/lso/openshift4-ose-kube-rbac-proxy
    source: registry.redhat.io/openshift4/ose-kube-rbac-proxy
  - mirrors:
    - quay.io/knarra/mynamespace/mynamespace1/lso/openshift4-ose-local-storage-diskmaker
    source: registry.redhat.io/openshift4/ose-local-storage-diskmaker
  - mirrors:
    - quay.io/knarra/mynamespace/mynamespace1/lso/redhat/redhat-operator-index
    source: registry.redhat.io/redhat/redhat-operator-index
  - mirrors:
    - quay.io/knarra/mynamespace/mynamespace1/lso/openshift4-ose-local-storage-operator
    source: registry.redhat.io/openshift4/ose-local-storage-operator
  - mirrors:
    - quay.io/knarra/mynamespace/mynamespace1/lso/openshift4-ose-local-storage-operator-bundle
    source: registry.redhat.io/openshift4/ose-local-storage-operator-bundle
```
11. Verify that if user sets an incorrect nested path below error is thrown
```
[fedora@preserve-fedora36 ~]$ sudo ./oc-mirror --config /tmp/config.yaml docker://quay.io/knarra/mynamespace/mynamespace1/lso --max-nested-paths=4
error: the max-nested-paths value (4) must be strictly higher than the number of path-components in the destination knarra/mynamespace/mynamespace1/lso - try increasing the value
```

**Pull request merged**
