### PR TITLE
CLID-122: upgrades distribution/distribution for a released version

### PR DESCRIPTION
**Pull request by aguidirh**
# Description

This PR upgrades the distribution/distribution to a version released in github ([v3.0.0-alpha.1](https://github.com/distribution/distribution/releases/tag/v3.0.0-alpha.1)) [which is the one recommended by the maintainers](https://github.com/distribution/distribution/discussions/4317#discussioncomment-8973790).

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes CVEs)

# How Has This Been Tested?

MirrorToMirror, MirrorToDisk and DiskToMirror on v2

It is necessary to still run the basic flows on v1.

## Expected Outcome

All the flows should finish successfully.

### CODE REVIEW

**Comment by aguidirh** [comment]
@lmzuccarelli the tests I did the hang issue did not happen. But as you know this issue does not happen always so maybe it is still there.

**Comment by aguidirh** [comment]
@kasturinarra and @zhouying7780 could you please test to see if there is no regression on v1? I tested only v2 flows.

**Comment by lmzuccarelli** [comment]
from my side it looks good (all tests are passing)

**Comment by sherine-k** [comment]
LGTM for me as well
:+1: 
Curious to learn more from your explanation on how to setup the registry log (it does look easier than before).

**Pull request merged**
