### PR TITLE
NO-ISSUE: Package ioutil is deprecated as of Go 1.16

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
The same functionality is now provided by package io or package os, and those implementations should be preferred in new code. Refer https://pkg.go.dev/io/ioutil for more details.

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Expected Outcome
Please describe the outcome expected from the tests

### CODE REVIEW

**Review by sherine-k — APPROVED** [review]
/lgtm

**Comment by sherine-k** [comment]
Thank you @LalatenduMohanty ;)

**Comment by sherine-k** [comment]
/rename NO-ISSUE: Package ioutil is deprecated as of Go 1.16

**Comment by sherine-k** [comment]
/retitle NO-ISSUE: Package ioutil is deprecated as of Go 1.16

**Review by aguidirh — COMMENTED** [review]
Thanks for your PR,

Could you please also change the following files which also contains the io/ioutil package? 

pkg/archive/archive_test.go
pkg/bundle/files_test.go
pkg/bundle/files.go
pkg/cincinnati/cincinnati.go
pkg/cli/options.go


Since oc-mirror keeps the vendor folder in the repo, please run make tidy and add the vendor folder changes to the commit in case of something has changes.

**Comment by LalatenduMohanty** [comment]
Fixed all ioutil calls in the code base as suggested. I have not touched the vendor folder as fixing the dependencies can be fixed separately.

**Comment by aguidirh** [comment]
@LalatenduMohanty thank you very much.

**Comment by aguidirh** [comment]
@LalatenduMohanty could you please rebase the PR so we can get it merged?

**Pull request merged**
