### PR TITLE
OCPBUGS-23550: - oc-mirror on RHEL9 Host with FIPS enabled

### PR DESCRIPTION
**Pull request by sherine-k**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # [OCPBUGS-23550](https://issues.redhat.com/browse/OCPBUGS-23550)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Expected Outcome
Please describe the outcome expected from the tests

### CODE REVIEW

**Comment by sherine-k** [comment]
/assign @jaypoulz @jupierce 
Hello to both,
I tried to follow the thread mentioned in https://issues.redhat.com/browse/OCPBUGS-23550. 
Is this the fix that you imagined? or are we missing anything?
Thank you for your help

**Comment by jaypoulz** [comment]
I think this is the crux of the change. I think Justin explains it in depth, here: https://redhat-internal.slack.com/archives/CFUGK0K9R/p1701891372146299

**Pull request merged**
