### PR TITLE
Fix flaky test Valid/OperatorTypeWithRelatedImgs

### PR DESCRIPTION
**Pull request by aguidirh**
# Description

This fix is for the test Valid/OperatorTypeWithRelatedImgs that was failing intermittently.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Verified the unit tests

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by lmzuccarelli** [comment]
Verified locally, tested this a couple of times (before and after regarding the change). Seems stable now as it was failing intermittently

@aguidirh - Thanks for the PR

**Review by lmzuccarelli — COMMENTED** [review]
/lgtm

**Review by lmzuccarelli — COMMENTED** [review]
Yes much more elegant. I should have investigated require in more depth.
Thanks again for the change  @aguidirh

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
