### PR TITLE
CLID-160,OCPBUGS-36569: upgrading containers/image, oc and library-go

### PR DESCRIPTION
**Pull request by aguidirh**
# Description

This PR contains all work needed to upgrade containers/image in oc-mirror. v1.

As oc-mirror v2 is using a released version of distribution/distribution v3, the distribution version was upgraded in oc and library-go as well (required because they are indirect dependencies in oc-mirror v1).

In this PR the oc-mirror is depending on an oc and library-go temporarily from a side branch (since the PR did not merge yet in oc and library-go). As soon as the PR gets merged, the two replaces in go.mod will be removed.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

go work sync
make build
make test-unit

## Expected Outcome
The commands above should pass successfully

### CODE REVIEW

**Review by sherine-k — APPROVED** [review]
Awesome @aguidirh !
This should have us covered until we completely cut oc-mirror v1 off. I hope it won't be a long time so that we don't stay on the fork for long.

**Comment by lmzuccarelli** [comment]
@aguidirh - Yes awesome work.  Thanks for doing this Alex

**Pull request merged**
