### PR TITLE
OCPBUGS-23479: fix e2e test for s390x

### PR DESCRIPTION
**Pull request by prb112**
# Description
Adds test artifacts for the s390x architecture

### CODE REVIEW

**Comment by lmzuccarelli** [comment]
@prb112 - seems like a nice easy change :)

**Comment by lmzuccarelli** [comment]
/retitle OCPBUGS-23479: fix e2e test for s390x

**Review by lmzuccarelli — APPROVED** [review]

**Comment by lmzuccarelli** [comment]
@aguidirh @sherine-k - could you add the "looks good to me" please

**Comment by prb112** [comment]
Thank you all, Paul

**Pull request merged**
