### PR TITLE
refactor(create): allow dry run option to run without failing

### LINKED ISSUE #206: [BUG] oc-mirror does not produce helpful information when using the dry run option
# Version

```console
$ oc-mirror version
v0.1.0-alpha.3
```

# What happened?
`oc-mirror` does not produce helpful information when using the `--dry-run` option

# What you expected to happen?

`oc-mirror` does not have a way to dry-run an entire operation and get results. 

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ ./bin/oc-mirror --config imageset-config.yaml file://demo --dry-run
```

# Anything else we need to know?

A plan file would be helpful for customers who would like a report of images to be downloaded before execution.

# References

### PR DESCRIPTION
**Pull request by jpower432**
# Description

This PR allows the dry-run option to run without failures due to image associations or creating an unwanted archive 

Partially fixes #206 

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [x] Unit test will be added

# Checklist:

- [X] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by estroz** [comment]
Shouldn't dry-runs do all the idempotent, local work? Not creating associations in memory seems like a failure of dry-run to make sure you config works.

**Comment by jpower432** [comment]
> Shouldn't dry-runs do all the idempotent, local work? Not creating associations in memory seems like a failure of dry-run to make sure you config works.

I think the only problem there is that when we create the associations, they are looking for the manifests in the disk so we would have to actually do the mirror which I think is counterintuitive for a dry run. I think there maybe be a way to mirror the manifests only which could probably work.

**Comment by estroz** [comment]
>it is looking for the manifests in the disk

Right I had forgotten. In that case what is being skipped is fine.

/lgtm

**Pull request merged**
