### PR TITLE
OCPBUGS-44901: Same tag format for helm, operators and additionalImages

### PR DESCRIPTION
**Pull request by lmzuccarelli**
# Description

This issue addresses the standard for all mirrored images on digests,  (update for helm)

Fixes # OCPBUGS-44901

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Use the following isc 

```
apiVersion: mirror.openshift.io/v2alpha1
kind: ImageSetConfiguration
mirror:
  helm:
    repositories:
      - name: sbo
        url: https://redhat-developer.github.io/service-binding-operator-helm-chart/

```

Execute a mirror to disk and disk to mirror

Once completed inspect the remote registry

```
curl http://localhost:5000/v2/ocpbugs-44901/redhat-developer/servicebinding-operator/tags/list | jq
```

## Expected Outcome

```
{
  "name": "ocpbugs-44901/redhat-developer/servicebinding-operator",
  "tags": [
    "16286ac84ddd521897d92472dae857a4c18479f255b725dfb683bc72df6e0865",
    "30bf7f0f21024bb2e1e4db901b1f5e89ab56e0f3197a919d2bbb670f3fe5223a",
    "67c2a2502f59fac1e7ded9ed19b59bbd4e50f5559a13978a87ecd2283b81e067",
    "69a95c6216ead931e01e4144ae8f4fb7ab35d1f68a14c18f6860a085ccb950f5",
    "ac47f496fb7ecdcbc371f8c809fad2687ec0c35bbc8c522a7ab63b3e5ffd90ea",
    "cc5aab01ddd3744510c480eb4f58b834936a833d36bec5c9c13fb40bbb06c663",
    "de1881753e82c51b31e958fcf383cb35b0f70f6ec99d402d42243e595d00c6dd",
    "e01016cacae84dfb6eaf7a1022130e7d95e2a8489c38d4d46e4f734848e93849",
    "e4259939a496f292a31b5e57760196d63a8182b999164d93a446da48c4ea24eb",
    "f79f6999a15534dbe56e658caf94fc4b7afb5ceeb7b49f32a60ead06fbd7c3fc"
  ]
}

```
Notice that the tags only reflect the digest (they don't have the sha256- prefix)

### CODE REVIEW

**Comment by sherine-k** [comment]
Hi @lmzuccarelli 
Let's rediscuss what tag strategy to keep with @aguidirh .
I got the impression that helm, but also sigstore use the same strategy (ie ${Algo}-${digest}) and that' s probably what we need to do for operator images and additional images going forward?
WDYT?

**Comment by aguidirh** [comment]
Hi @lmzuccarelli,

Currently the format of release tags is `fmt.Sprintf("%s-%s", imgSpec.Algorithm, imgSpec.Digest)` see [here](https://github.com/openshift/oc-mirror/blob/33e51c5ce34382425608af77a0642376df2e15c5/v2/internal/pkg/release/local_stored_collector.go#L562)

So I would suggest to keep helm as it was before (same format as release) and change the operator and additional images tag to follow the helm/release format (when by digest only).

In this way all the tags generated by oc-mirror when digest only follow the same format.

**Comment by lmzuccarelli** [comment]
@aguidirh - yes sure that makes sense, I'll go ahead and change it

**Pull request closed without merging**
