### PR TITLE
Write oc Run() output to logfile

### PR DESCRIPTION
**Pull request by afflom**
# Description

Writes all oc Run() log output to log file and not stdout/stderr because oc Run() functions write all logs to stderr, which overrides expected IOSTREAMS configured output. 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Locally

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by estroz — CHANGES_REQUESTED** [review]
Forcing output to be written to a file doesn't feel right. Why can't `oc-mirror` just do what other `oc` commands do?

**Comment by afflom** [comment]
> Forcing output to be written to a file doesn't feel right. Why can't `oc-mirror` just do what other `oc` commands do?

https://github.com/openshift/oc/blob/93bc841b10af165df15d07d2ab7ce04b85e63ca5/pkg/cli/image/mirror/mirror.go#L295 

oc forces most messages to stderr. This is a workaround for TP. Long term, we need a logging interface and oc needs to log to something else.

**Comment by jpower432** [comment]
/hold
Putting on hold while we figure the best solution for this milestone

**Pull request closed without merging**
