### PR TITLE
OCPBUGS-15329: Fix " OCI index found, but accept header does not suppo…"

### PR DESCRIPTION
**Pull request by sherine-k**
…rt OCI indexes

# Description

Mirroring using the following imageSetConfig results in an error:

```bash
oc-mirror --config certified-operator-index-imageset-conf-v4.12.yaml file://tmp/operator/
```
```yaml
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  local:
    path: /tmp/mirror
mirror:
  operators:
    - catalog: registry.redhat.io/redhat/certified-operator-index:v4.12
      targetName: certified-operator-index-06-20-2023-00-00-00
      packages:
        - name: kubeturbo-certified
          channels:
            - name: 'stable'
              maxVersion: '8.9.2'
              minVersion: '8.9.2'
```
Error message:
```
error: unable to retrieve source image icr.io/cpopen/kubeturbo-operator manifest sha256:cc6499b8c5c7a3dfd829d75d7bc73fca6c467bfb5e3235e62018e7ef18220a21: unknown: OCI index found, but accept header does not support OCI indexes
error: an error occurred during planning
```
Fixes OCPBUGS-15329

## Type of change

The fix consists of accepting OCI indexes  while building mirroring metadata and creating layer associations....

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

End to End manual test using the imageSetConfig provided above.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by sherine-k** [comment]
@zhouying7780 The thing I'm not sure about is:
* mirroring from archive to registry with the content generated by this mirroring
* incremental mirroring (a second iteration of mirroring using the same storageConfig)
I would really appreciate it if you can verify that these 2 scenarios don't break with this fix.
Thank you so much for your help

**Comment by yuvalkoushnir** [comment]
Same behavior is happening when using community-operator-index:v4.10

**Comment by sherine-k** [comment]
Hi @yuvalkoushnir 
Thanks for the feedback.
Do you mean that with the PR in this fix you still reproduce the issue for `opentelemetry-operator`?
Thank you

**Comment by yuvalkoushnir** [comment]
Hi @sherine-k 
My oc-mirror binary version is as follows
```
Client Version: version.Info{Major:"", Minor:"", GitVersion:"4.13.0-202306060829.p0.ge06d309.assembly.stream-e06d309", GitCommit:"e06d3097f7d73bf8e987cfb161ce872bab57e019", GitTreeState:"clean", BuildDate:"2023-06-06T08:52:10Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}
```
Also this version does not contain the following flags so i cannot use them
```
--use-oci-feature 
--oci-feature-action=copy
```

**Comment by sherine-k** [comment]
Hi @zhouying7780 
Can you help validate this fix?
Thank you so much

**Comment by zhouying7780** [comment]
done pre-merge test , no issue found

**Pull request merged**
