### PR TITLE
feat: adds implementation for --manifest-only flags to mirror command

### LINKED ISSUE #314: [RFE] Output manifests only
oc-mirror should ingest imageset metadata independent of an imageset and output kubernetes resources that inform a cluster how to consume resources from a referenced mirror.

### PR DESCRIPTION
**Pull request by jpower432**
The implementation for the --manifest-only flags will read the metadata
from a given imageset and generated any required manifests and write them
to a results directory.

Closes #314

Signed-off-by: Jennifer Power <barnabei.jennifer@gmail.com>

# Description

^^

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [X] Adds NoManifest cases to `mirror` unit tests
- [X] Adds unit tests for the conversion to `TypedImageMetadata`
- [X] Adds unit test for `MetadataFromFile` method

# How to Test
```
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  local:
   path: metadata
mirror:
  additionalimages:
    - name: registry.redhat.io/ubi8/ubi:latest
```
```
oc-mirror --config imageset-config.yaml file://archives
oc-mirror --from archives/mirror_seq1_000000.tar docker://localhost:5000 --manifests-only
```

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by afflom — APPROVED** [review]
This generated the manifests without performing mirroring as expected. @deejross, over to you.

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Review by dinhxuanvu — COMMENTED** [review]
/lgtm

**Pull request merged**
