### PR TITLE
OCPBUGS-14402: Fix case where catalog is on a mirror from registries…

### PR DESCRIPTION
**Pull request by sherine-k**
….conf

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # OCPBUGS-14402

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Unit and E2E pass
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by lmzuccarelli** [comment]
@sherine-k - verified locally no ```server gave HTTP response to HTTPS client``` errors

**Comment by zhouying7780** [comment]
done pre-merged test with latest pr https://github.com/openshift/oc-mirror/pull/682/files , now could follow the oci-registries-config and get from localhost registry with http

**Pull request merged**
