### PR TITLE
fix(config): cleaned up config keys, made naming and defaults more intuitive

### PR DESCRIPTION
**Pull request by estroz**
# Description

- `version/bundle []string -> startingVersion/startingBundle string`
- remove unused index handling keys, since these modes will not be supported

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] unit tests
- [x] e2e tests

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by jpower432 — COMMENTED** [review]
Tested and everything works as expected and in line with the updated documentation. One nit, what do you think about changing the `headsOnly` key to `latestOnly`?

**Comment by estroz** [comment]
That could be cleaner, yeah, although I think the term "latest" here is not clear. Wdyt about "diffFromLastRun" or something self-explanatory. @afflom thoughts?

**Comment by afflom** [comment]
> That could be cleaner, yeah, although I think the term "latest" here is not clear. Wdyt about "diffFromLastRun" or something self-explanatory. @afflom thoughts?

latest is problematic because of channels. diff is problematic because that assumes that users understand that concept. Though I have questioned if most users understand the concept of channel/git HEAD, I think that it might be the most precise. I think everyone understands the concept of an upgrade. what if we make a boolean called upgrade that is true by default and correlate it with packages? This is on my mind: https://issues.redhat.com/browse/WRKLDS-281#:~:text=Messer%0A%20added%20a-,comment,--%2011%20hours%20ago

**Review by jpower432 — APPROVED** [review]
After some discussions, I think we have agreed that `headsOnly` can stay.

**Pull request merged**
