### PR TITLE
feat(catalogs): add catalog target name and tag

### PR DESCRIPTION
**Pull request by jpower432**
# Description

This PR adds the ability to set a target name and tag on catalogs. This also removed the requirement to set full when mirroring by package.

Related to #332 

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [X] Unit tests and E2E added to test thing 

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by afflom — APPROVED** [review]
works as advertised. Also, pruning functions as expected if the catalog source changes.

**Review by dinhxuanvu — APPROVED** [review]
This PR can be benefited by my new HeadsOnly PR on registry but another PR can carry that change later.
/lgtm

**Comment by jpower432** [comment]
> This PR can be benefited by my new HeadsOnly PR on registry but another PR can carry that change later. /lgtm
Copy on this @dinhxuanvu. That PR should be #438.

**Pull request merged**
