### PR TITLE
[release-4.12] OCPBUGS-13432: Got the `file exists` error when different digest direct to the same tag

### PR DESCRIPTION
**Pull request by sherine-k**
* Fix OCPBUGS-2633

* Revert "Fix OCPBUGS-2633"

This reverts commit a1a3b82159f8a2d436a41cd10486e35250f77153.

* Fix OCPBUGS-2633 keeping scope of fix to MirrorToDisk only

---------

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by kasturinarra** [comment]
Below are the steps i have followed to pre-merge test the bug:
==================================================
1. Install latest 4.12 oc-mirror nightly
2. Create imagesetconfig.yaml as shown below
```
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
# archiveSize: 4
mirror:
  additionalImages:
    - name: brew.registry.redhat.io/rh-osbs/openshift-ose-cluster-kube-descheduler-operator-bundle@sha256:46a62d73aeebfb72ccc1743fc296b74bf2d1f80ec9ff9771e655b8aa9874c933
    - name: brew.registry.redhat.io/rh-osbs/openshift-ose-cluster-kube-descheduler-operator-bundle@sha256:9e549c09edc1793bef26f2513e72e589ce8f63a73e1f60051e8a0ae3d278f394
    - name: brew.registry.redhat.io/rh-osbs/openshift-ose-cluster-kube-descheduler-operator-bundle@sha256:c16891ee9afeb3fcc61af8b2802e56605fff86a505e62c64717c43ed116fd65e
    - name: brew.registry.redhat.io/rh-osbs/openshift-ose-cluster-kube-descheduler-operator-bundle@sha256:5c37bd168645f3d162cb530c08f4c9610919d4dada2f22108a24ecdea4911d60
    - name: brew.registry.redhat.io/rh-osbs/openshift-ose-cluster-kube-descheduler-operator-bundle@sha256:89a6abbf10908e9805d8946ad78b98a13a865cefd185d622df02a8f31900c4c1
    - name: brew.registry.redhat.io/rh-osbs/openshift-ose-cluster-kube-descheduler-operator-bundle@sha256:de5b339478e8e1fc3bfd6d0b6784d91f0d3fbe0a133354be9e9d65f3d7906c2d
    - name: brew.registry.redhat.io/rh-osbs/openshift-ose-cluster-kube-descheduler-operator-bundle@sha256:fdf774c4365bde48d575913d63ef3db00c9b4dda5c89204029b0840e6dc410b1
    - name: brew.registry.redhat.io/openshift4/ose-cluster-kube-descheduler-operator@sha256:d90aecc425e1b2e0732d0a90bc84eb49eb1139e4d4fd8385070d00081c80b71c
    - name: brew.registry.redhat.io/openshift4/ose-descheduler@sha256:15cc75164335fa178c80db4212d11e4a793f53d2b110c03514ce4c79a3717ca0
    - name: brew.registry.redhat.io/openshift4/ose-cluster-kube-descheduler-operator@sha256:9e66db3a282ee442e71246787eb24c218286eeade7bce4d1149b72288d3878ad
    - name: brew.registry.redhat.io/openshift4/ose-descheduler@sha256:546b14c1f3fb02b1a41ca9675ac57033f2b01988b8c65ef3605bcc7d2645be60
    - name: brew.registry.redhat.io/openshift4/ose-cluster-kube-descheduler-operator@sha256:12d7061012fd823b57d7af866a06bb0b1e6c69ec8d45c934e238aebe3d4b68a5
    - name: brew.registry.redhat.io/openshift4/ose-descheduler@sha256:41025e3e3b72f94a3290532bdd6cabace7323c3086a9ce434774162b4b1dd601
    - name: brew.registry.redhat.io/openshift4/ose-cluster-kube-descheduler-operator@sha256:672b4bee759f8115e5538a44c37c415b362fc24b02b0117fd4bdcc129c53e0a1
    - name: brew.registry.redhat.io/openshift4/ose-descheduler@sha256:92542b22911fbd141fadc53c9737ddc5e630726b9b53c477f4dfe71b9767961f
    - name: brew.registry.redhat.io/openshift4/ose-cluster-kube-descheduler-operator@sha256:f6b6a15c4477615ff202e73d77fc339977aeeca714b9667196509d53e2d2e4f5
    - name: brew.registry.redhat.io/openshift4/ose-descheduler@sha256:1feb7073dec9341cadcc892df39ae45c427647fb034cf09dce1b7aa120bbb459
    - name: brew.registry.redhat.io/openshift4/ose-cluster-kube-descheduler-operator@sha256:7ca05f93351959c0be07ec3af84ffe6bb5e1acea524df210b83dd0945372d432
    - name: brew.registry.redhat.io/openshift4/ose-descheduler@sha256:c0fe8830f8fdcbe8e6d69b90f106d11086c67248fa484a013d410266327a4aed
    - name: brew.registry.redhat.io/openshift4/ose-cluster-kube-descheduler-operator@sha256:6a1de43c60d021921973e81c702e163a49300254dc3b612fd62ed2753efe4f06
    - name: brew.registry.redhat.io/openshift4/ose-descheduler@sha256:b386d0e1c9e12e9a3a07aa101257c6735075b8345a2530d60cf96ff970d3d21a
```

4. create directory called test using the command `mkdir test`
5. Run the command `oc-mirror --config /tmp/imagesetconfig.yaml file://home/knarra/test/`
6. See that error can be reproduced
     ```
sha256:672b4bee759f8115e5538a44c37c415b362fc24b02b0117fd4bdcc129c53e0a1 file://openshift4/ose-cluster-kube-descheduler-operator:latest
error: unable to push manifest to file://openshift4/ose-cluster-kube-descheduler-operator:latest: symlink sha256:9e66db3a282ee442e71246787eb24c218286eeade7bce4d1149b72288d3878ad home/knarra/test/oc-mirror-workspace/src/v2/openshift4/ose-cluster-kube-descheduler-operator/manifests/latest.download: file exists
error: unable to push manifest to file://openshift4/ose-cluster-kube-descheduler-operator:latest: symlink sha256:6a1de43c60d021921973e81c702e163a49300254dc3b612fd62ed2753efe4f06 home/knarra/test/oc-mirror-workspace/src/v2/openshift4/ose-cluster-kube-descheduler-operator/manifests/latest.download: file exists
info: Mirroring completed in 5m45.37s (7.988MB/s)
error: one or more errors occurred while uploading images
```

Tested with latest oc-mirror bits in 4.12 branch:
=======================================
1. git clone https://github.com/openshift/oc-mirror.git
2. checkout release-4.12 branch `git checkout release-4.12`
3. gh pr checkout 641
4. make build which generates oc-mirror in bin directory
5. create imagesetconfig.yaml as shown below

```
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
# archiveSize: 4
mirror:
  additionalImages:
  - name: quay.io/okd/scos-content@sha256:fc37fb091804ce32411d04559a4b0ba63139bd12b51f7d87dc2e8fa9ff9d3ef7
  - name: quay.io/okd/scos-content@sha256:df80aa07467d1c6f59a39f3c00e00e130a6b25308b1419264565ca7cd8a76407
```

7. create directory called test1 using the command `mkdir test1`
8. Run the command `oc-mirror --config /tmp/imagesetconfig.yaml file://home/knarra/test1`
9. see that error cannot be reproduced and things work fine
     
```
info: Planning completed in 2.63s
uploading: file://okd/scos-content sha256:2e7c4173d931d7cc039747f0790ed11fba42f964d8e7d0b05b7808e782ed0564 11.79MiB
uploading: file://okd/scos-content sha256:97a6159bc677aa2abbc3d0222cdbb9be39615af67c88b46f1d9aa0150a83f47a 23.64KiB
uploading: file://okd/scos-content sha256:6f70be2ee17ebb8c71b862a5f364a8c9cd39901fd2c039dc226152bca81e4bfd 23.09KiB
uploading: file://okd/scos-content sha256:4534f7f2788cb7ed1abd839410c90e8fb95d2145c5add2d0646021c546a75786 30.87MiB
uploading: file://okd/scos-content sha256:716e739ca7cb8dbc09187be2bdeed93262653996e0b13f5936e4e909ef99a4b4 463.2KiB
uploading: file://okd/scos-content sha256:97da74cc6d8fa5d1634eb1760fd1da5c6048619c264c23e62d75f3bf6b8ef5c4 75.84MiB
uploading: file://okd/scos-content sha256:50c5caf281eb1792409d447284cca3df93b1f0c5f56c8ff34c0fa5708db44f0d 465.1KiB
uploading: file://okd/scos-content sha256:622ceb2281df8e15e9ffdfb635b2eb3e00360b7aee3e47c67e6fdc747471133a 11.79MiB
uploading: file://okd/scos-content sha256:067f126180dff2d087953bfe776a38a1b5923fcffd5bbe13074938df2ef67a3d 25.44MiB
uploading: file://okd/scos-content sha256:0e8721c30137905641e58cf7943f058a1eb679814c8ad3541bd85892bf7667c9 24.62MiB
sha256:df80aa07467d1c6f59a39f3c00e00e130a6b25308b1419264565ca7cd8a76407 file://okd/scos-content:df80aa07
sha256:fc37fb091804ce32411d04559a4b0ba63139bd12b51f7d87dc2e8fa9ff9d3ef7 file://okd/scos-content:fc37fb09
info: Mirroring completed in 27.3s (6.961MB/s)
Creating archive /home/knarra/oc-mirror/home/knarra/oc-mirror/test_bug1/mirror_seq1_000000.tar
```

**Review by soltysh — APPROVED** [review]
/approve
/label backport-risk-assessed

**Pull request merged**
