### PR TITLE
CLID-135: Show warning in console when EUS & version conditions used

### PR DESCRIPTION
**Pull request by lmzuccarelli**
# Description

This addresses the issue when mirroring platform releases using the **eus** channel, oc-mirror does not yet implement `conditionalEdges` and as a result will not correctly select the version/s for a complete upgrade path.

A warning message will be displayed in the console when an eus channel with minor versions >= 2 are selected.

This applies to both v1 and v2 versions of oc-mirror

Addresses # [OCPSTRAT-1306](https://issues.redhat.com//browse/OCPSTRAT-1306)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

To verify use the following imagesetconfig for v1 of oc-mirror

```
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
mirror:
  platform:
    graph: true # Required for the OSUS ooperator
    architectures:
    - amd64
    channels:
    - name: stable-4.12
      minVersion: '4.12.28'
      maxVersion: '4.12.28'
      shortestPath: true
      type: ocp
    - name: eus-4.14
      minVersion: '4.12.28'
      maxVersion: '4.14.16'
      shortestPath: true
      type: ocp
```

For v2

```
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  platform:
    graph: true # Required for the OSUS ooperator
    architectures:
    - amd64
    channels:
    - name: stable-4.12
      minVersion: '4.12.28'
      maxVersion: '4.12.28'
      shortestPath: true
      type: ocp
    - name: eus-4.14
      minVersion: '4.12.28'
      maxVersion: '4.14.16'
      shortestPath: true
      type: ocp
```

## Expected Outcome
Warning message in console should appear

For v1

```
bin/oc-mirror --config clid-135.yaml file://clid-135 
Found: clid-135/oc-mirror-workspace/src/publish
Found: clid-135/oc-mirror-workspace/src/v2
Found: clid-135/oc-mirror-workspace/src/charts
Found: clid-135/oc-mirror-workspace/src/release-signatures
backend is not configured in clid-135.yaml, using stateless mode
backend is not configured in clid-135.yaml, using stateless mode
No metadata detected, creating new workspace
WARNING: Extended Update Support (EUS) channel detected with minor version range >= 2
	 Please refer to the web console https://access.redhat.com/labs/ocpupgradegraph/update_path
	 To correctly determine the upgrade path for EUS releases
```

For v2

```
bin/oc-mirror --config clid-135.yaml file://clid-135 --v2

2024/06/07 11:02:39  [WARN]   : ⚠️  --v2 flag identified, flow redirected to the oc-mirror v2 version. This is Tech Preview, it is still under development and it is not production ready.
2024/06/07 11:02:39  [INFO]   : 👋 Hello, welcome to oc-mirror
2024/06/07 11:02:39  [INFO]   : ⚙️  setting up the environment for you...
2024/06/07 11:02:39  [INFO]   : 🔀 workflow mode: mirrorToDisk 
2024/06/07 11:02:40  [INFO]   : 🕵️  going to discover the necessary images...
2024/06/07 11:02:40  [INFO]   : 🔍 collecting release images...
2024/06/07 11:02:40  [WARN]   : Extended Update Support (EUS) channel detected with minor version range >= 2
				Please refer to the web console https://access.redhat.com/labs/ocpupgradegraph/update_path
				To correctly determine the upgrade path for EUS releases
```

### CODE REVIEW

**Comment by sherine-k** [comment]
LGTM !

**Review by aguidirh — APPROVED** [review]
Thank you very much, nice and simple.

**Review by aguidirh — APPROVED** [review]
Thank you very much, nice and simple.

**Pull request merged**
