### PR TITLE
OCPBUGS-7465: Fix 401 Unauthorized due to stale auth token

### LINKED ISSUE #526: Error 401 when operations take more than 5min
# Version

```console
$ oc-mirror version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"4.11.0-202210262118.p0.g3c1c80c.assembly.stream-3c1c80c", GitCommit:"3c1c80ca6a5a22b5826c88897e7a9e5acd7c1a96", GitTreeState:"clean", BuildDate:"2022-10-27T00:32:32Z", GoVersion:"go1.18.4", Compiler:"gc", Platform:"linux/amd64"}
```

# What happened?

```
error: error rendering new refs: render reference "registry.redhat.io/redhat/redhat-operator-index:v4.11": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry.redhat.io/v2/redhat/redhat-operator-index/blobs/sha256:144af1563390e9a694f66e8065b32e12ab836b1412de7fdf423996a229b00d21: 401 Unauthorized - Server message: unauthorized: Access to the requested resource is not authorized
```

# What did you expect to happen?

When operations are too long i experience 401 error

# How to reproduce it (as minimally and precisely as possible)?

Use `cpulimit` to artificially make tasks longer

```console
$  cpulimit -l 1 ./oc-mirror --config config.yml docker://localhost:5000 --dest-skip-tls --dest-use-http --verbose 9
```

# Anything else we need to know?

my `config.yml`
```
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  registry:
    imageURL: localhost:5000/metadata:latest
    skipTLS: true
mirror:
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.11
      packages:
        - name: loki-operator
        - name: elasticsearch-operator
        - name: odf-operator
```

I suspect that after 5min auth with registry expire and there no refresh mecanism.

### PR DESCRIPTION
**Pull request by everettraven**
# Description

Creating this PR with changes made by @grokspawn (originally started this work but had to transition to focus on other things so I took over) that:
- refactors the conditional code compilation to use go build tags to ignore building for windows (necessary for being able to compile on MacOS)
- bumps the operator-framework/operator-registry dependency to v1.29.0 and fixes necessary unit tests

Fixes #526 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

This was tested by manually trying to reproduce the problem found in #526 by performing the following steps:
1. `./hack/build.sh` to build a binary with the changes
2. Create a local image registry with `docker run -d -p 5001:5000 --restart=always --name registry registry`
3. Create an oc-mirror config file named `oc-mirror-config.yaml` with contents:
```yaml
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  registry:
    imageURL: localhost:5001/metadata:latest
    skipTLS: true
mirror:
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.11
      packages:
        - name: loki-operator
        - name: elasticsearch-operator
        - name: odf-operator
```
4. Running the oc-mirror binary with the changes:
```
./bin/oc-mirror --config ~/testing/oc-mirror/oc-mirror-config.yaml docker://localhost:5001 --dest-skip-tls --dest-use-http --verbose 9 2>&1 | tee /tmp/oc-mirror-attempt.txt
```

Checking the output from step 4 a second 401 unauthorized response is encountered and then 200 OK statuses are retrieved in subsequent requests and the command exits successfully.

> **Note**: This was a preliminary test and more testing is being done to verify this effectively resolves the problem. This PR is being opened as a draft to allow for others to more easily run tests for verification.

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by lmzuccarelli** [comment]
@everettraven - thanks for submitting this PR, we have a couple of frustrated users that want this fix. Much appreciated !!!

**Comment by lmzuccarelli** [comment]
@zhouying7780 - could you verify this PR when you get a chance. Once we have your thumbs up we can move it out of WIP

**Comment by everettraven** [comment]
Just to update - @grokspawn and  I both did the same test specified in the PR description using `cpulimit -l 50 ...` to slow the process down even further to ensure we hit a token refresh and both our tests ended up successfully hitting a second 401 status response, refreshing (appears to occur silently because we don't see logs for that request), and continuing with 200s and successfully exiting

**Comment by everettraven** [comment]
@lmzuccarelli @sherine-k Are there any concerns with marking this as "Ready for review" to run CI?

**Comment by sherine-k** [comment]
Thank you for the hard work !
I tried /unhold, but please if you can remove the draft flag so that this can pass CI, let's do that...

**Comment by sherine-k** [comment]
@zhouying7780 would you mind also taking a look ?
This PR will probably be backported at least to 4.14 and 4.13

**Comment by everettraven** [comment]
@sherine-k I marked this PR as "Ready for Review" to take it out of the draft state.

**Comment by grokspawn** [comment]
Thought to solve #526

**Pull request merged**
