### PR TITLE
CFE-902 feat: removes go workspace due to incompatibility on ART builds

### PR DESCRIPTION
**Pull request by aguidirh**
# Description

Go workspace was introduced in PR #[670](https://github.com/openshift/oc-mirror/pull/670) but it is not supported by ART builds so this PR is to remove go workspaces.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by lmzuccarelli — APPROVED** [review]
Looks good - thanks @aguidirh

**Comment by sherine-k** [comment]
/lgtm
@joepvd This PR should provide a replacement for the go workspace from PR 670.
Can you please let us know if it fixes ART builds?
Thank you

**Pull request merged**
